Only sync metas of sync tax
polylang/polylang pull request #1005
Opened 2022-04-07 11:05 UTC by Marianne380

Fix https://github.com/polylang/polylang-pro/issues/1143

Metas were synchronized for unsynchronized taxonomies.
**Now**, metas are only synchronized for synchronized taxonomies.

`$from` and `$to` were added for consistency and safety.
`pll_get_term()` is now checked.

2022-04-07 14:14 UTC, Chrystll commented
The PR triggers a fatal error below when trying to translate a post into another language. 

```
PHP Fatal error:  Uncaught Error: Call to protected method PLL_Sync_Tax::get_taxonomies_to_copy() from context 'PLL_WPSEO' in /home/christelle/Documents/git/polylang/integrations/wpseo/wpseo.php:446
Stack trace:
#0 /wp-includes/class-wp-hook.php(309): PLL_WPSEO->copy_post_metas(Array, false, 25, 49)
#1 /wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /home/christelle/Documents/git/polylang/modules/sync/sync-post-metas.php(78): apply_filters('pll_copy_post_m...', Array, false, 25, 49, 'en')
#3 /home/christelle/Documents/git/polylang/modules/sync/sync-metas.php(351): PLL_Sync_Post_Metas->get_metas_to_copy(25, 49, 'en', false)
#4 /home/christelle/Documents/git/polylang/modules/sync/admin-sync.php(107): PLL_Sync_Metas->copy(25, 49, 'en')
#5 /wp-includes/class-wp-hook.php(309): PLL_Admin_Sync->new_post_translation(true)
#6 /wp-includes/plugin.php in /home/christelle/Documents/git/polylang/integrations/wpseo/wpseo.php on line 446
```

2022-04-08 09:59 UTC, Screenfeed requested changes

2022-04-08 09:59 UTC, Screenfeed commented on integrations/wpseo/wpseo.php
>  		return $value;
`PLL()->model->is_translated_taxonomy( $key )` won't work, it's the full name of the meta with the prefix `'_yoast_wpseo_primary_'`.

```php
if ( 0 !== strpos( $key, '_yoast_wpseo_primary_' ) ) {
	return $value;
}

$taxonomy = str_replace( '_yoast_wpseo_primary_', '', $key );

if ( ! PLL()->model->is_translated_taxonomy( $taxonomy ) ) {
	return $value;
}

return pll_get_term( $value, $lang );
```

2022-04-08 10:01 UTC, Marianne380 commented on modules/sync/sync-tax.php
> +	public function get_taxonomies_to_copy( $sync, $from = null, $to = null, $lang = null ) {
Good idea :+1:

2022-04-08 10:44 UTC, Screenfeed approved these changes

2022-04-08 13:37 UTC, merged