Clean useless JS and centralize function
polylang/polylang pull request #1011
Opened 2022-04-12 13:58 UTC by Marianne380

Fix https://github.com/polylang/polylang-pro/issues/742

Remove useless part of JS code concerning the metabox. (the language selector and the translations table were modified while the page was being refreshed right after).

Centralization of the `initTranslations()` function to avoid duplication.

2022-04-22 14:31 UTC, manooweb requested changes

2022-04-22 14:31 UTC, manooweb commented on js/src/block-editor.js
> +							function() {
It seems to me we can just call `blockEditorSavePostAndReloadPage()` without making the ajax call i.e. directly after clicking the confirmation button in the dialog box.
Indeed as we don't need to refresh the metabox and the code to do that was removed, it also not required to make the ajax call.

2022-04-22 14:43 UTC, manooweb commented
Also look at PHPCS Error https://app.travis-ci.com/github/polylang/polylang/jobs/566822293, please

2022-04-26 10:48 UTC, manooweb requested changes

2022-04-26 10:48 UTC, manooweb commented on js/src/block-editor.js
> +						blockEditorSavePostAndReloadPage();
Sorry but `data` variable above used in the ajax call is also useless.

2022-04-26 11:55 UTC, manooweb approved these changes
ok 👌

2022-04-26 13:50 UTC, merged

2022-04-27 15:18 UTC, Chrystll commented
That's Ok for me. I didn't detect any issue. Here are the done tests.

Test with Polylang Pro 3.3-dev and the Legacy metabox for block editor mode that I set in the wp-config.php define('PLL_USE_BLOCK_EDITOR_PLUGIN', false);
**_Block editor mode_**
Test 1: create a new post > don't fill a title and don't save it > change language > the page is reloaded
- check you get the Polylang notice: no but this the expected behavior when there isn't any title filled and the post is not saved
- check the categories, tags and Media Library are re-loaded in the right language : yes
- check autocomplete field, you should get the title in the right language : yes


Test 2: create a new post > fill a title and save it > change language > the page is reloaded
- check you get the Polylang notice: yes
- check the categories and tags and Media Library are re-loaded in the right language : yes
- check autocomplete field, you should get the title in the right language : yes

**_Classic editor mode_**
Test 3: create a new post > don't fill a title and don't save it > change language > the page is not reloaded
- check you get the Polylang notice : no but this the expected behavior when there isn't any title filled and the post is not saved
- check the categories, tags and Media Library are re-loaded in the right language :  yes
- check autocomplete field, you should get the title in the right language : yes

Test 4: create a new post > fill a title and save it > change language > the page is reloaded
- check you get the Polylang notice: yes
- check the categories, tags and Media Library are re-loaded in the right language : yes
- check autocomplete field, you should get the title in the right language : yes