Revert PR #1125 set_pre_term_slug() method code
polylang/polylang pull request #1136
Opened 2022-10-07 08:21 UTC by manooweb

All is in the title.

Even if the PR #1125 fixed the https://github.com/polylang/polylang-pro/issues/1468 it triggers some other issues especailly revealed by some Polylang Pro shared slugs PHPUnit tests which break.

Accordingly the issue has been [reopened](https://github.com/polylang/polylang-pro/issues/1468#issuecomment-1271206929) and need to be fixed another way.

2022-10-07 13:52 UTC, Screenfeed requested changes

2022-10-07 13:52 UTC, Screenfeed commented on include/crud-terms.php
> +		 * @param string            $taxonomy Term taonomy.
We could at least fix this typo 😅
```suggestion
		 * @param string            $taxonomy Term taxonomy.
```

2022-10-07 13:52 UTC, Screenfeed commented on include/crud-terms.php
> +
```suggestion

```

2022-10-07 13:52 UTC, Screenfeed commented on include/crud-terms.php
> +		if ( ! $slug ) {
Since `$slug` is not a boolean, I would prefer to see `empty()`, but no obligations:
```suggestion
		if ( empty( $slug ) ) {
```

2022-10-10 09:20 UTC, Screenfeed approved these changes

2022-10-12 12:55 UTC, closed without merging

2022-10-12 13:04 UTC, Chouby commented
Closed in favor of #1139