Get rid of deprecated PLL_Language properties.
polylang/polylang pull request #1167
Opened 2022-12-15 11:57 UTC by Marianne380

Remove direct call to deprecated properties and use `PLL_Language::get_tax_prop()` instead.

2022-12-16 10:50 UTC, Screenfeed requested changes
Some are missing:
- https://github.com/polylang/polylang/blob/11a25e1862455212108f93aadbfef6950a08ed54/include/query.php#L112
- https://github.com/polylang/polylang/blob/11a25e1862455212108f93aadbfef6950a08ed54/settings/table-languages.php#L71-L72
- https://github.com/polylang/polylang/blob/11a25e1862455212108f93aadbfef6950a08ed54/integrations/wp-sweep/wp-sweep.php#L56 This one will require to loop through the language taxonomies to add the `term_id` of `language`, `term_language`, `wc_order_language`, etc.
- https://github.com/polylang/polylang/blob/11a25e1862455212108f93aadbfef6950a08ed54/frontend/frontend-filters.php#L82
- https://github.com/polylang/polylang/blob/11a25e1862455212108f93aadbfef6950a08ed54/include/model.php#L148

2022-12-19 14:07 UTC, Screenfeed approved these changes

2022-12-19 16:15 UTC, Chouby requested changes

2022-12-19 16:15 UTC, Chouby commented on integrations/wp-sweep/wp-sweep.php
>  		);
You can do much simpler by:
1. Avoiding a direct call to `getIterator()`. It's for PHP, you probably never it.
2. Avoiding an intermediate array ( again ;) )
3. Use `get_tax_prop**s**()` which definitely kills the bullet 1.

```php
		// Add the terms of our languages.
		foreach ( $languages as $language ) {
			$excluded_term_ids = array_merge(
				$excluded_term_ids,
				$language->get_tax_props( 'term_id' );
			);
		}
```

2022-12-20 14:41 UTC, merged