Don't reset the"static front page" option on deletion of a home page translation
polylang/polylang pull request #1311
Opened 2023-06-29 15:15 UTC by Screenfeed

Fixes https://github.com/polylang/polylang-pro/issues/1701.

This PR allows to disable/enable the translation of the options `page_for_posts` and `page_on_front` whenever we want. This is done with the methods `PLL_Static_Pages::disable_page_on_front_and_page_for_posts_translation()` and `PLL_Static_Pages::enable_page_on_front_and_page_for_posts_translation()`.

This PR also disables these translations automatically when deleting the page for posts, page on front, or one of their translations. This is done by "surrounding" `_reset_front_page_settings_for_post()`, which is hooked to `before_delete_post` and `wp_trash_post`.

Note: maybe `disable_page_on_front_and_page_for_posts_translation()` could be used directly in place of `maybe_disable_page_on_front_and_page_for_posts_translation()`, but it feels safer (at least to me) to keep it.

2023-06-30 08:04 UTC, Hug0-Drelon requested changes

2023-06-30 08:04 UTC, Hug0-Drelon commented on tests/phpunit/tests/test-static-pages.php
Should we add a test for page deletion without translation?

2023-07-03 08:28 UTC, Screenfeed commented on include/static-pages.php
> +	public function disable_page_on_front_and_page_for_posts_translation() {
Not strictly necessary but it felt weird to me to have one public and the other private.

2023-07-03 08:28 UTC, Screenfeed commented on include/static-pages.php
> +		add_action( 'before_delete_post', array( $this, 'enable_page_on_front_and_page_for_posts_translation' ), 10000 );
Won't work, we can't add a hook from inside this hook.

2023-07-03 08:37 UTC, Screenfeed commented on tests/phpunit/tests/test-static-pages.php
Would you expect a different behavior?

2023-07-03 09:35 UTC, Hug0-Drelon commented on include/static-pages.php
> +	public function disable_page_on_front_and_page_for_posts_translation() {
You're right, let's be consistent.

2023-07-03 09:36 UTC, Hug0-Drelon commented on tests/phpunit/tests/test-static-pages.php
No, but I would prevent to have a different one in the future having this case covered.

2023-07-12 09:11 UTC, Screenfeed commented on tests/phpunit/tests/test-static-pages.php
Done in [f285bac](https://github.com/polylang/polylang/pull/1311/commits/f285bac386768202384dd2b0f332db11019fa954).

2023-07-12 15:24 UTC, Hug0-Drelon approved these changes

2023-07-18 09:44 UTC, Chouby commented
Would it work to simply test `doing_action( 'before_delete_post' )` and `doing_action( 'wp_trash_post' )` in `translate_page_on_front()` and `translate_page_for_posts()` as we already do for `switch_blog`? This would be much simpler. This would also be less precise but I expect side effects to be unlikely.

2023-07-19 08:30 UTC, Screenfeed commented
> Would it work to simply test `doing_action( 'before_delete_post' )` and `doing_action( 'wp_trash_post' )` in `translate_page_on_front()` and `translate_page_for_posts()` as we already do for `switch_blog`? This would be much simpler. This would also be less precise but I expect side effects to be unlikely.

Indeed, less precise but much simpler. Done in [7ad209f](https://github.com/polylang/polylang/pull/1311/commits/7ad209fc7ee8be4d9e71d4076bf3274ab1a8bfb7).

2023-07-19 15:45 UTC, merged