E2E tests for Polylang Wizard and languages creation as well as settings panel.
polylang/polylang pull request #1320
Opened 2023-07-18 09:56 UTC by Hug0-Drelon

## How?
- Add test for language creation within the wizard and the languages panel.
- Add test for each modules within the settings panel.
- Make `env-set-up.spec.js` a dependency for all other tests.

2023-07-19 09:14 UTC, manooweb requested changes

2023-07-24 07:41 UTC, Hug0-Drelon commented on tests/e2e/specs/create-languages/create-languages.spec.js
> +		await page.getByRole('link', { name: 'Languages' }).first().click();
Indeed, done in4af17df6.

2023-07-24 07:41 UTC, Hug0-Drelon commented on tests/e2e/specs/create-languages/create-languages.spec.js
> +		await page.getByRole('link', { name: 'Languages' }).first().click();
Removed in 4af17df6.

2023-07-24 08:19 UTC, manooweb approved these changes
ok 👌

2023-07-25 15:18 UTC, Chouby commented on tests/e2e/specs/settings/settings-table.spec.js
> +		// Active "Detect browser language" module then test it can be deactivated.
```suggestion
		// Activate "Detect browser language" module then test it can be deactivated.
```

2023-07-26 08:09 UTC, Hug0-Drelon commented on tests/e2e/specs/settings/settings-table.spec.js
> +		// Open URL modifications options panel and test each ones are accessible.
Indeed, I'll add a comment telling it's when plain permalinks is enabled.
Do you want to add test for pretty permalinks as well?

2023-07-26 08:13 UTC, Hug0-Drelon commented on tests/e2e/specs/create-languages/create-languages.spec.js
> +		await expect( page.getByRole('cell', { name: 'Français Edit | Delete' }), 'French should be visible in the table.').toBeVisible();
Done in 84f4853c.

2025-05-05 09:28 UTC, Hug0-Drelon commented
e2e are done in `polylang/polylang-pro`, closed in favor of https://github.com/polylang/polylang-pro/pull/2453.

2025-05-05 09:28 UTC, closed without merging