Translate the content of the widget custom html
polylang/polylang pull request #1423
Opened 2024-02-14 18:05 UTC by Chouby

WP 4.8.1 introduced the widget custom html which works more or less like the widget text.
The content honors the filter 'widget_text'.
However it is stored in DB with the key 'content' instead of 'text'. So we fail to register the string in the strings translation panel.

In this PR, we register the string corresponding to the widget content when the widget is displayed in all languages.
It also includes minor formatting enhancements.

2024-02-14 19:30 UTC, szepeviktor commented on admin/admin-strings.php
> +					if ( ! empty( $title ) ) {
`empty` does `isset` internally.
```php
if ( ! empty( $widget_settings[ $number ]['title'] ) ) {
```

2024-03-13 09:11 UTC, Hug0-Drelon requested changes

2024-03-13 09:11 UTC, Hug0-Drelon commented on admin/admin-strings.php
> +				}
```suggestion
				// Text of the Widget text.
				if ( ! empty( $widget_settings[ $number ]['text'] ) ) {
					self::register_string( self::$default_strings['widget_text'], $widget_settings[ $number ]['text'], 'Widget', true );
				}
```
Follows previous @szepeviktor suggestion.

2024-03-13 09:11 UTC, Hug0-Drelon commented on admin/admin-strings.php
>  				}
```suggestion
				if ( ! empty( $widget_settings[ $number ]['content'] ) ) {
					self::register_string( self::$default_strings['widget_text'], $widget_settings[ $number ]['content'], 'Widget', true );
				}
```
Same as above.

2024-04-09 08:50 UTC, Chouby commented on admin/admin-strings.php
>  					}
```suggestion
				if ( ! empty( $widget_settings[ $number ]['title'] ) ) { 
					self::register_string( self::$default_strings['widget_title'], $widget_settings[ $number ]['title'], 'Widget' );
```

2024-04-09 10:35 UTC, Hug0-Drelon approved these changes

2024-04-09 15:04 UTC, merged