is Polylang network activated or not ?
polylang/polylang pull request #1446
Opened 2024-03-15 15:05 UTC by sebastienserre

In a Multisite context, add a test if Polylang is network activated or not

2024-12-31 12:02 UTC, Chouby requested changes
I would rather move this new section to `info()` as this is not related to Polylang options.

2024-12-31 12:02 UTC, Chouby commented on modules/site-health/admin-site-health.php
> +			if ( is_plugin_active_for_network( 'polylang/polylang.php' ) || is_plugin_active_for_network( 'polylang-pro/polylang.php' )){
Use `POLYLANG_BASENAME` instead

2024-12-31 12:02 UTC, Chouby commented on modules/site-health/admin-site-health.php
> +				$network_activated = __( 'Yes', 'polylang' );
I know translations are more performant now however an `if() ... else` would avoid you to translate 2 stings when only one is necessary.

2025-08-13 14:19 UTC, closed without merging

2025-08-13 14:28 UTC, sebastienserre commented
Replaced by #1712