Adds a condition not to update page_on_front and page_for_posts options
polylang/polylang pull request #1512
Opened 2024-07-23 07:23 UTC by manooweb

fixes https://github.com/polylang/polylang-pro/issues/2178

Explanations are coming soon ...

## How?
Adds a condition not to update page_on_front and page_for_posts options with translated ids when these options are being updated.

2024-07-23 11:54 UTC, Screenfeed approved these changes

2024-07-23 12:56 UTC, Chouby commented on include/static-pages.php
> +		if ( doing_action( 'update_option_page_on_front' ) || doing_action( 'switch_blog' ) || doing_action( 'before_delete_post' ) || doing_action( 'wp_trash_post' ) ) {
Could complete comments and add a test?

2024-07-25 08:50 UTC, Chouby requested changes

2024-07-25 08:50 UTC, Chouby commented on include/static-pages.php
> +		if ( doing_action( 'update_option_page_on_front' ) || doing_action( 'switch_blog' ) || doing_action( 'before_delete_post' ) || doing_action( 'wp_trash_post' ) ) {
```suggestion
		if ( doing_action( "update_option_{$option}" ) || doing_action( 'switch_blog' ) || doing_action( 'before_delete_post' ) || doing_action( 'wp_trash_post' ) ) {
```

2024-07-25 08:50 UTC, Chouby commented on tests/phpunit/tests/test-translate-page-for-posts.php
>  		$this->assertEquals( $en, $return );
```suggestion
		$this->assertSame( $en, get_option( 'page_for_posts' ) );
```

2024-07-25 08:50 UTC, Chouby commented on tests/phpunit/tests/test-translate-page-for-posts.php
>  		$this->assertEquals( $fr, $return );
```suggestion
		$this->assertSame( $fr, get_option( 'page_for_posts' ) );
```

2024-07-25 08:50 UTC, Chouby commented on tests/phpunit/tests/test-translate-page-for-posts.php
>  		$this->assertEquals( $en, $return );
```suggestion
		$this->assertSame( $en, get_option( 'page_for_posts' ) );
```

2024-07-25 11:07 UTC, manooweb commented on include/static-pages.php
> +		if ( doing_action( 'update_option_page_on_front' ) || doing_action( 'switch_blog' ) || doing_action( 'before_delete_post' ) || doing_action( 'wp_trash_post' ) ) {
🙄

2024-07-25 14:23 UTC, merged