Allow numbers in language code
polylang/polylang pull request #1546
Opened 2024-09-23 08:32 UTC by Chouby

`es-419` is a valid locale (Spanish for Latin America and Caribbean islands). It would make sense to use `es-419` as language code for this locale. Thus this PR allow numbers in language code. Interesting side effect: we will have the same characters allowed as in `sanitize_key()` that we use to sanitize language codes.

2024-09-23 08:49 UTC, Screenfeed requested changes
The same pattern is used in several places to match language code/slug, they should all be modified the same way.

By searching `[a-z_-]+`:
- In PLL: 7 matches.
- In PLL Pro: 2 matches (1 in JS).
- In PLL WC: 0 matches.

2024-09-23 14:38 UTC, Screenfeed approved these changes

2024-09-23 14:53 UTC, merged

2025-04-02 14:39 UTC, Chrystll commented
OK, a format like es-419 works. 
@Chouby from what I understand, 419 alone cannot be used because a language code must always start with a language identifier, and "419" alone is not recognized as a language. Is it right?

2025-04-02 14:48 UTC, Chouby commented
Yes the first character is mandatorily a lowercase letter `[a-z]` For the other characters, the same letters are accepted + numbers + `-` + `_`.