Fix "Language is defined from the content" front page
polylang/polylang pull request #1564
Opened 2024-10-14 10:25 UTC by Screenfeed

Fixes https://github.com/polylang/polylang-pro/issues/2294.

## Issue

When the language is defined from the content, the home page and the CPT archive pages are not translated, they display content in default language. The home page even redirects to the default language home page.

## What happens

Props @Chouby for finding the cause of this issue.

When registering the language taxonomy in `PLL_Translated_Post::register_language_taxonomy()` since #1359, the global `$wp` doesn't exist yet, which leads `WP_Taxonomy::add_rewrite_rules()` to fail to add the query var [here](https://github.com/WordPress/WordPress/blob/00a39b7510b97b76c86768b0c0ba4ecb9797534b/wp-includes/class-wp-taxonomy.php#L503).

## Solution

The solution suggested here consists on re-add the query var when the global `$wp` is ready.

2024-10-16 11:05 UTC, Hug0-Drelon approved these changes

2024-10-28 14:55 UTC, Hug0-Drelon commented on tests/phpunit/tests/test-choose-lang-content.php
> +		$en = self::factory()->post->create( array( 'post_date' => '2007-09-04 00:00:00' ) );
Is the date mandatory?

2024-10-28 15:26 UTC, Hug0-Drelon approved these changes

2024-10-28 18:08 UTC, Chouby requested changes

2024-10-29 09:51 UTC, Screenfeed commented on tests/phpunit/tests/test-choose-lang-content.php
> +		do_action( 'setup_theme' );
It was my concern (not specific to `post_format` though) but it doesn't trigger any issues in this series of tests.
Anyway, added in [cdc7480](https://github.com/polylang/polylang/pull/1564/commits/cdc7480a45568afb9d41dfe121098d27e828571d).

2024-10-29 15:56 UTC, merged