Don't add language_attributes filter on log in page
polylang/polylang pull request #1601
Opened 2024-12-20 15:49 UTC by manooweb

fixes https://github.com/polylang/polylang-pro/issues/2420

## What?

It's seems that `determine_locale()`  WordPress function already manage `wp_lang` dropdown & cookie for the log in page.
So it's useless Polylang modify the language attributes in this case.
See https://github.com/WordPress/WordPress/blob/6.7.1/wp-includes/l10n.php#L139-L147

## How?
- Adds a condition not to add our filter in this case.

2025-01-27 14:06 UTC, Marianne380 requested changes

2025-01-27 14:06 UTC, Marianne380 commented on include/filters.php
> +			return $output;
Shouldn't we convert the WordPress locale to W3C locale in this case too?

2025-08-28 10:24 UTC, manooweb commented on include/filters.php
> +			return $output;
By using `determine_locale()` instead of `get_locale()`, the condition is useless and thus we ensure W3C conversion if the language exists in Polylang. Otherwise the WordPress value is kept.
See the latest commit: 42c25efb3bbdf3dba36cfc40be23c5d5060d01ef

> [!NOTE]
> A language can be displayed in the list even if it doesn't exist in Polylang. The list is based on the translation files existence.

2025-08-29 09:02 UTC, Marianne380 requested changes

2025-08-29 09:02 UTC, Marianne380 commented on include/filters.php
> +		if ( $language = $this->model->get_language( is_admin() ? get_user_locale() : determine_locale() ) ) {
Can we take the opportunity to remove the assignment in the `if` statement?

2025-08-29 09:30 UTC, manooweb commented on include/filters.php
> +		if ( $language = $this->model->get_language( is_admin() ? get_user_locale() : determine_locale() ) ) {
Sure! Done in 8d59f0ec543ad7511f822d3bee17566f8e09fbc1

2025-08-29 09:35 UTC, Marianne380 approved these changes

2025-08-29 13:26 UTC, Chouby commented on include/filters.php
> +		$language = $this->model->get_language( is_admin() ? get_user_locale() : determine_locale() );
IMHO `determine_locale()` should be sufficient. See https://github.com/WordPress/wordpress-develop/blob/6.8.2/src/wp-includes/l10n.php#L153
```suggestion
		$language = $this->model->get_language( determine_locale() );
```

Could you add a test?

2025-09-01 10:15 UTC, manooweb commented on include/filters.php
> +		$language = $this->model->get_language( is_admin() ? get_user_locale() : determine_locale() );
Done in 9f54b15b084a9fc9df32b0eaa51170c63b2683ec & bc466d9d810afcff87c102f817f4c6f000b363a1

2025-09-01 12:17 UTC, merged