Webpackization build from sources
polylang/polylang pull request #675
Opened 2020-12-17 11:16 UTC by raaaahman

## Before

Javascript files where built as `<original_file_name>.min.js` whether they were actually minified or not.

## Changes

Replaces #663 

- Javascript files with the `.src` suffix will be built in both minified and non-minified versions.
- Javascript files without any suffix will be minified
- Javascript files with the `.dep` suffix will never be built nor minified. They are only meant to be imported into other files.

## Going further

This method forces us to manually add the files built from source to the `.gitignore` list, as there are actually no differences between `.js` files that are built from sources and those that doesn't need to be built at all.

2020-12-23 15:24 UTC, manooweb commented
🤔 Strange bin/build.sh and bin/distribute.sh are commited as empty and they mustn't because they doesn't have to override ones on master branch

2020-12-23 15:39 UTC, manooweb requested changes

2020-12-23 15:39 UTC, manooweb commented on .gitignore
> +*.map
Rule already exists on master just above `*.min.js` rule

2020-12-23 15:39 UTC, manooweb commented on webpack/FileNames.js
> +	function mapJsFiles( jsFileNames, minimize = false ) {
Shouldn't we define these functions outside the `getJsFileNamesEntries()` one ?

2020-12-24 09:58 UTC, raaaahman commented
> Strange bin/build.sh and bin/distribute.sh are commited as empty and they mustn't because they doesn't have to override ones on master branch

That's the diff files that is empty, because the files content didn't change. But the files permissions did (from 774 to 644). Don't know if it would be an issue though...

2020-12-24 10:06 UTC, manooweb commented
> > Strange bin/build.sh and bin/distribute.sh are commited as empty and they mustn't because they doesn't have to override ones on master branch
> 
> That's the diff files that is empty, because the files content didn't change. But the files permissions did (from 774 to 644). Don't know if it would be an issue though...

🤔 OK. I launch this bash scripts in my linux WSL kernel and I haven't any problem with permission on them. Is it the case on your team's linux environment ?

2020-12-24 10:16 UTC, raaaahman commented
Well 644 is not executable, so this is a problem indeed...

2021-01-20 14:56 UTC, raaaahman commented
Replaced by #726

2021-01-20 14:56 UTC, closed without merging