Browser preferred language update
polylang/polylang pull request #711
Opened 2021-01-11 11:15 UTC by raaaahman

## Before

Our Browser Preferred Language detection could only work with language and region information transmitted from WordPress visitors' browser agents, like 'en-GB' or 'zh-CN'.

It used to detect incomplete matches where either the 'language' or 'region' information matched one of the languages sent in the Accept-Language HTTP Header, given that the websites used **only one tag** in their slugs, like 'gb' or 'zh'.

Fixes #591

## Changes

- Updates 'Accept-Language' HTTP Header parsing to be compatible with [BCP 47](https://tools.ietf.org/html/bcp47#section-2.1)
- Allows our detection to match website's languages with close Accept-Languages values, including:
  - A 'language' only match
  - A 'language-region' match
  - A 'region' only match
  - A 'language-variant' match
 - Improve consistency of Preferred Language detection with custom slugs.

## Going further

Should we only match languages that are set as 'actives' when used in Polylang Pro?

2021-02-05 10:36 UTC, Marianne380 approved these changes

2021-02-08 14:10 UTC, Chouby requested changes

2021-02-08 14:10 UTC, Chouby commented on frontend/choose-lang.php
> +			$accept_langs = PLL_Accept_Languages_Collection::from_accept_language_header( sanitize_text_field( $_SERVER['HTTP_ACCEPT_LANGUAGE'] ) );
Add `wp_unslash()`.

2021-02-09 12:05 UTC, merged

2021-07-29 04:29 UTC, alvinhochun commented
Hi, thanks for making the changes to fix the issue. I believe our site currently has Polylang 3.0.6 installed, however which should include the changes here, but for some reason `zh-Hant-HK` in accept-language still redirects me to the `zh_CN` version of the site, any idea on how it could be happening?

This is our language settings:
![圖片](https://user-images.githubusercontent.com/2397650/127431680-91824bbb-3f4e-49a8-9303-69ccc9b13e89.png)


```console
$ curl -H "Accept-Language: zh-Hant-HK" https://krita.org/ -s -D - -o /dev/null | grep -i location:
location: https://krita.org/zh/

$ curl -H "Accept-Language: zh-HK" https://krita.org/ -s -D - -o /dev/null | grep -i location:
location: https://krita.org/zh-hk/
```

2021-08-03 13:12 UTC, raaaahman commented
Indeed, the results seems to be dependent on the order in which the languages are queried from the database:

https://github.com/polylang/polylang/blob/ce90849b24b459b4d0589a215b2b2eae75cf900d/frontend/accept-languages-collection.php#L138

We should perform a 'weighted comparison' instead. Example: matching language is worth 1000, matching region 100, matching script 10, etc. And the highest value is returned.