Legacy widgets filters
polylang/polylang pull request #736
Opened 2021-02-01 16:29 UTC by raaaahman

WIP fixes https://github.com/polylang/polylang-pro/issues/836

To do:

- Instantiate just in time, in hope this would allow us not to override an existing instance.
- Shouldn't we check for not being in a Page Builder on the front-end, but in a different manner than how it is done in the admin context?

2021-02-03 13:27 UTC, manooweb requested changes
Just rename PLL_Widgets_Options_Filters_Admin maybe ?

**/!\ Note** that in the new widget screen when add a legacy widget the first time, languages field - if modified - isn't save correctly due to the issue on widget form fields reported in https://github.com/WordPress/gutenberg/issues/28668

We need to refresh the new widget screen, then change the languages and update again to really take the language in account.

2021-02-03 13:27 UTC, manooweb commented on admin/widgets-options-filters-admin.php
> +class PLL_Widgets_Options_Filters_Admin extends PLL_Widgets_Options_Filters {
Shouldn't we name it PLL_Admin_Widgets_Options_Filters ? To respect how we name all the other class

2021-02-03 13:27 UTC, manooweb commented on admin/widgets-options-filters-admin.php
> +		if ( ! empty( $_POST[ $key ] ) ) { // phpcs:ignore WordPress.Security.NonceVerification
👍 Note in the context of the legacy widget screen, it seems that the $new_instance doesn't contains the $key element - name of the languages field. Its for that we have to retrieve the value for the $_POST global variable.

2021-02-03 16:37 UTC, Chouby requested changes

2021-02-03 16:37 UTC, Chouby commented on include/widgets-options-filters.php
> +	 * @since 3.0 Moved from PLL_Admin_Filters
Same as above for `@since`.

2021-02-03 16:37 UTC, Chouby commented on include/widgets-options-filters.php
> +	 * @return string
Please add `@since` and description for the param.

2021-02-03 16:37 UTC, Chouby commented on include/widgets-options-filters.php
> + */
Please add `@since`

2021-02-03 16:37 UTC, Chouby commented on include/widgets-options-filters.php
> +	 */
Same as above for `@since`. Also please add the removed short description for parameters.

2021-02-03 16:37 UTC, Chouby commented on include/widgets-options-filters.php
> +class PLL_Widgets_Options_Filters {
For consistency with other class names, I suggest to use `PLL_Filters_Widgets_Options`.

2021-02-03 16:37 UTC, Chouby commented on include/rest-request.php
> +	public $widgets_filters;
Same as above for the property name.

2021-02-03 16:37 UTC, Chouby commented on include/widgets-options-filters.php
> + * Class PLL_Widgets_Filters
Not the right class name.

2021-02-03 16:37 UTC, Chouby commented on include/widgets-options-filters.php
> +	 * PLL_Widgets_Filters constructor.
Not the right class name.

2021-02-04 10:56 UTC, manooweb approved these changes

2021-02-05 10:00 UTC, merged