Add test to improve coverage for PLL_Admin_Default_Term
polylang/polylang pull request #889
Opened 2021-06-30 11:44 UTC by Marianne380

This method https://github.com/polylang/polylang/blob/3.1-beta1/admin/admin-default-term.php#L250-L267 wasn't covered by a test.

2021-06-30 13:57 UTC, Screenfeed commented on tests/phpunit/tests/test-default-term.php
> +		self::$model->update_default_lang( $es->slug );
Wouldn't it be simpler to do this?
```suggestion
		self::$model->update_default_lang( 'es' );
```

2021-06-30 15:32 UTC, Screenfeed approved these changes

2021-06-30 16:39 UTC, Chouby requested changes
The method `update_default_lang()` is doing more than what you check. Your test would passes with any Spanish category becoming default. In fact, the new default category is the Spanish translation of the previous default category. Could you check that too?

2021-07-02 11:59 UTC, Chouby approved these changes

2021-07-02 11:59 UTC, merged